[phases.install]
cmds = ["cd backend && pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["cd backend && npx prisma generate", "cd backend && pnpm build"]

[start]
cmd = "cd backend && node dist/src/main"
